language: php
php:
  - nightly
  - hhvm
  - 7.1
  - 7.0
  - 5.6
matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer update --no-interaction --prefer-dist
  - COMPOSER_ROOT_VERSION=dev-master composer require --dev codeclimate/php-test-reporter:dev-master

script:
  - ./vendor/phpunit/phpunit/phpunit -v --coverage-clover build/logs/clover.xml

after_script:
  - CODECLIMATE_REPO_TOKEN=5687c9ab7944bc3d96d0cd59459870da6bb6059f3be5c03a690713bbbf1c5d4a ./vendor/bin/test-reporter